### ISSUE TITLE
next send2cgeo release

### ISSUE THREAD

**Issue by bekuno** [cgeo/send2cgeo#90]
I think we have now reached a good state to be ready for a new release.
- Solved Issues:
  - [x] #44 extended line height for premium caches in basic member list view
  - [X] #66 send2cgeo on old map stops opening the cache details
  - [X] #68 send2cgeo only works in english on the browsemap
  - [X]  #77 s2cgeo does't work on recentlyviewed and nearest list
  - [X]  #81 GCLH2 does not work while send2cgeo got new update
  - [X]  #82 Non-functional change of coordinates
  - [X]  #85 s2cg button after loging a cache
  - [x] #93 premiumCheck() does not work
- with PR:
  - [X] #83 use .href.match() 
  - [X] #86 Solve Problems after switch to jQuery
  - [X] #87 s2cgeo does't work on recentlyviewed and nearest list
  - [X] #88 s2cg button after loging a cache
  - [X] #91 send2cgeo only works in english on the browsemap
  - [X] #92 Fit on the cache detail button to rest of the script.
  - [x] #94 premiumCheck and alignment at the new search

Is something missed here?

**Comment by capoaira** [comment]
I think so too.
No, nothing missing here, but I have 2 new, little PRs:
- #91 / #68 send2cgeo only works in english on the browsemap
- #92 Fit on the cache detail button to rest of the script

**Comment by capoaira** [comment]
I've fix to other bugs:
 - #94 / #93 premiumCheck() does not work
- #94 / #44 No misalignment in the new search for PM-Caches

**Comment by Lineflyer** [comment]
Will merge branches next weekend when back home. Internet connection is not the best here in Madagascar.

**Comment by Lineflyer** [comment]
Thanks @capoaira for your efforts to fix and improve. Really highly appreciated as the script was not really maintained for a longer time.

**Comment by capoaira** [comment]
Madagascar sounds cool. Have fun!

**Comment by Lineflyer** [comment]
Back home.
I have not tested anything myself, but I have read in my mails, that the current status of `master` should be good.
Do I have your OK to raise version number and release to users by merging branch to `release`?

**Comment by bekuno** [comment]
@Lineflyer welcome home.
Please see the check list above.
PR #92 is ok now and ready to merge. After that you can release a new release.

**Comment by Lineflyer** [comment]
Version has been raised to 0.49. Branch `master` has been merged to branch `release` thus 0.49 is live for users to update.
